---
- hosts: localhost
  tasks:

  - name: "Echo text"
    shell: "echo 'hello world !'"
    register: print_text
    tags: test

  - debug: msg="{{ print_text.stdout_lines }}"

  - name: "Create file"
    ansible.builtin.file:
      path: /home/krishan/test.txt
      state: touch
      #mode: u=rw,g=r,o=r
